import logging
import time

from .. import config, llm_client, prompts
from ..gitlab_client import GitLabClient
from ..reviewer import split_diffs
from ._common import notify_and_save

log = logging.getLogger(__name__)


async def handle_mr_description(project_id: int, mr_iid: int, project_name: str) -> bool:
    t_start = time.monotonic()
    log.info("========== MR DESCRIPTION GENERATION START ==========")
    log.info("Project: %s (id=%s) | MR: !%s", project_name, project_id, mr_iid)

    async with GitLabClient() as gl:
        try:
            mr = await gl.get_mr(project_id, mr_iid)
        except Exception:
            log.exception("  Failed to fetch MR metadata")
            return False

        description = (mr.get("description") or "").strip()
        if description:
            log.info("  MR already has a description (%d chars), skipping", len(description))
            return False

        log.info("  MR has empty description, generating one...")

        try:
            diffs = await gl.get_diffs(project_id, mr_iid)
        except Exception:
            log.exception("  Failed to fetch diffs")
            return False

        if not diffs:
            log.info("  No diffs found, skipping")
            return False

        title = mr.get("title") or f"MR !{mr_iid}"
        source_branch = mr.get("source_branch") or "unknown"
        target_branch = mr.get("target_branch") or "unknown"

        chunks = split_diffs(diffs, config.MAX_CHUNK_CHARS)
        diff_block = "\n\n".join(chunks)

        log.info("  Generating description with LLM...")
        t_llm = time.monotonic()
        try:
            generated = await llm_client.chat([
                {"role": "system", "content": prompts.MR_DESCRIPTION_SYSTEM},
                {"role": "user", "content": prompts.MR_DESCRIPTION_PROMPT.format(
                    title=title,
                    source_branch=source_branch,
                    target_branch=target_branch,
                    diff_block=diff_block,
                )},
            ])
        except Exception:
            log.exception("  LLM generation failed")
            return False
        log.info("  LLM responded in %.1fs", time.monotonic() - t_llm)

        auto_note = f"\n\n---\n_Description auto-generated by `{config.OLLAMA_MODEL}`._"
        new_description = generated + auto_note

        try:
            await gl.update_mr(project_id, mr_iid, description=new_description)
            log.info("  Updated MR description (%d chars)", len(new_description))
        except Exception:
            log.exception("  Failed to update MR description")
            return False

    mr_url = mr.get("web_url", "")
    await notify_and_save(
        event_type="mr_description", project_id=project_id, project_name=project_name,
        title=f"MR !{mr_iid} — {title}",
        url=mr_url, result_text=generated, ref_id=str(mr_iid),
    )

    log.info("========== MR DESCRIPTION DONE in %.1fs ==========", time.monotonic() - t_start)
    return True
