import logging
import time

from .. import llm_client, prompts
from ..gitlab_client import GitLabClient
from ._common import notify_and_save

log = logging.getLogger(__name__)


async def _handle_release_for_tag(project_id: int, project_name: str, tag: str,
                                  project_web_url: str) -> None:
    t_start = time.monotonic()
    log.info("========== RELEASE NOTES START ==========")
    log.info("Project: %s | Tag: %s", project_name, tag)

    model = await llm_client.model_for_project(project_id)

    async with GitLabClient() as gl:
        try:
            tags = await gl.get_tags(project_id)
        except Exception:
            log.exception("  Failed to fetch tags")
            return

        tag_names = [t["name"] for t in tags]
        current_idx = None
        for i, name in enumerate(tag_names):
            if name == tag:
                current_idx = i
                break

        if current_idx is None:
            log.warning("  Tag '%s' not found in tag list, skipping", tag)
            return

        previous_tag = tag_names[current_idx + 1] if current_idx + 1 < len(tag_names) else None

        if previous_tag:
            log.info("  Previous tag: %s", previous_tag)
        else:
            log.info("  No previous tag found — this is the first release")

        comparison: dict = {}
        if previous_tag:
            try:
                comparison = await gl.compare(project_id, previous_tag, tag)
            except Exception:
                log.exception("  Failed to compare refs")

        commits = comparison.get("commits") or []
        log.info("  Found %d commits between tags", len(commits))

        commits_block = "\n".join(
            f"- `{c.get('short_id', c.get('id', '')[:8])}` {c.get('title', '')}"
            for c in commits
        ) or "(no commits found or first release)"

        try:
            mrs = await gl.list_merge_requests(project_id, state="merged")
            if previous_tag:
                prev_tag_date = None
                for t in tags:
                    if t["name"] == previous_tag:
                        commit_info = t.get("commit") or {}
                        prev_tag_date = commit_info.get("created_at") or commit_info.get("committed_date")
                        break
                if prev_tag_date:
                    mrs = [m for m in mrs if m.get("merged_at") and m["merged_at"] > prev_tag_date]
            else:
                mrs = mrs[:50]
        except Exception:
            log.exception("  Failed to fetch MRs")
            mrs = []

        log.info("  Found %d merged MR(s) in range", len(mrs))

        mrs_block = "\n".join(
            f"- !{m.get('iid', '?')} — {m.get('title', 'untitled')} "
            f"(by {m.get('author', {}).get('username', '?')})"
            for m in mrs
        ) or "(no merged MRs found)"

        log.info("  Generating release notes with LLM...")
        t_llm = time.monotonic()
        try:
            notes = await llm_client.chat([
                {"role": "system", "content": prompts.RELEASE_NOTES_SYSTEM},
                {"role": "user", "content": prompts.RELEASE_NOTES_PROMPT.format(
                    tag=tag,
                    previous_tag=previous_tag or "(none — first release)",
                    mrs_block=mrs_block,
                    commits_block=commits_block,
                )},
            ], model=model)
        except Exception:
            log.exception("  LLM generation failed")
            return
        log.info("  LLM responded in %.1fs", time.monotonic() - t_llm)

        auto_note = f"\n\n---\n_Generated by `{model}`._"
        full_notes = notes + auto_note

        try:
            await gl.update_release(project_id, tag, full_notes)
            log.info("  Updated release description for tag '%s'", tag)
        except Exception:
            log.warning("  Could not update release (release may not exist yet for tag '%s')", tag)

    tag_url = f"{project_web_url}/-/tags/{tag}" if project_web_url else ""
    await notify_and_save(
        event_type="release_notes", project_id=project_id, project_name=project_name,
        title=f"Release {tag}",
        url=tag_url, result_text=notes, ref_id=tag, model=model,
    )

    log.info("========== RELEASE NOTES DONE in %.1fs ==========", time.monotonic() - t_start)


async def handle_release(payload: dict) -> None:
    action = payload.get("action")
    if action != "create":
        log.info("Release ignored: action=%s (only processing creates)", action)
        return

    project = payload.get("project") or {}
    project_id = project.get("id")
    project_name = project.get("path_with_namespace") or project.get("name") or "unknown"
    tag = payload.get("tag") or ""

    if not project_id or not tag:
        log.info("Release ignored: missing project_id or tag")
        return

    await _handle_release_for_tag(project_id, project_name, tag, project.get("web_url", ""))


async def handle_tag_push(payload: dict) -> None:
    project = payload.get("project") or {}
    project_id = project.get("id")
    project_name = project.get("path_with_namespace") or project.get("name") or "unknown"
    ref = payload.get("ref", "")
    tag = ref.replace("refs/tags/", "")

    checkout_sha = payload.get("checkout_sha") or payload.get("after", "")
    if not checkout_sha or checkout_sha == "0" * 40:
        log.info("Tag push ignored: tag '%s' was deleted", tag)
        return

    if not project_id or not tag:
        log.info("Tag push ignored: missing project_id or tag")
        return

    await _handle_release_for_tag(project_id, project_name, tag, project.get("web_url", ""))
