import logging
import time

from .. import config, db, google_chat, llm_client, prompts
from ..gitlab_client import GitLabClient

log = logging.getLogger(__name__)


async def _handle_release_for_tag(project_id: int, project_name: str, tag: str,
                                  project_web_url: str) -> None:
    t_start = time.monotonic()
    log.info("========== RELEASE NOTES START ==========")
    log.info("Project: %s | Tag: %s", project_name, tag)

    gl = GitLabClient()

    try:
        tags = await gl.get_tags(project_id)
    except Exception:
        log.exception("  Failed to fetch tags")
        return

    tag_names = [t["name"] for t in tags]
    current_idx = None
    for i, name in enumerate(tag_names):
        if name == tag:
            current_idx = i
            break

    if current_idx is None:
        log.warning("  Tag '%s' not found in tag list, skipping", tag)
        return

    previous_tag = tag_names[current_idx + 1] if current_idx + 1 < len(tag_names) else None

    if previous_tag:
        log.info("  Previous tag: %s", previous_tag)
    else:
        log.info("  No previous tag found — generating notes from all history")

    from_ref = previous_tag or ""
    try:
        if from_ref:
            comparison = await gl.compare(project_id, from_ref, tag)
        else:
            comparison = await gl.compare(project_id, tags[-1]["name"] if tags else "HEAD~50", tag)
    except Exception:
        log.exception("  Failed to compare refs")
        comparison = {}

    commits = comparison.get("commits") or []
    log.info("  Found %d commits between tags", len(commits))

    commits_block = "\n".join(
        f"- `{c.get('short_id', c.get('id', '')[:8])}` {c.get('title', '')}"
        for c in commits
    ) or "(no commits)"

    try:
        if previous_tag:
            mrs = await gl.list_merge_requests(project_id, state="merged")
            prev_tag_date = None
            for t in tags:
                if t["name"] == previous_tag:
                    commit_info = t.get("commit") or {}
                    prev_tag_date = commit_info.get("created_at") or commit_info.get("committed_date")
                    break

            if prev_tag_date:
                mrs = [m for m in mrs
                       if m.get("merged_at") and m["merged_at"] > prev_tag_date]
        else:
            mrs = await gl.list_merge_requests(project_id, state="merged", per_page=50)
    except Exception:
        log.exception("  Failed to fetch MRs")
        mrs = []

    log.info("  Found %d merged MR(s) in range", len(mrs))

    mrs_block = "\n".join(
        f"- !{m.get('iid', '?')} — {m.get('title', 'untitled')} (by {m.get('author', {}).get('username', '?')})"
        for m in mrs
    ) or "(no merged MRs found)"

    log.info("  Generating release notes with LLM...")
    t_llm = time.monotonic()
    try:
        notes = await llm_client.chat([
            {"role": "system", "content": prompts.RELEASE_NOTES_SYSTEM},
            {"role": "user", "content": prompts.RELEASE_NOTES_PROMPT.format(
                tag=tag,
                previous_tag=previous_tag or "(none — first release)",
                mrs_block=mrs_block,
                commits_block=commits_block,
            )},
        ])
    except Exception:
        log.exception("  LLM generation failed")
        return
    log.info("  LLM responded in %.1fs", time.monotonic() - t_llm)

    auto_note = f"\n\n---\n_Generated by `{config.OLLAMA_MODEL}`._"
    full_notes = notes + auto_note

    try:
        await gl.update_release(project_id, tag, full_notes)
        log.info("  Updated release description for tag '%s'", tag)
    except Exception:
        log.warning("  Could not update release (release may not exist yet for tag '%s')", tag)

    tag_url = f"{project_web_url}/-/tags/{tag}" if project_web_url else ""

    try:
        webhook_config = await db.get_webhook_config(project_id)
        if webhook_config and webhook_config.get("enabled"):
            await google_chat.send_event(
                event_type="release_notes", body=notes,
                title=f"Release {tag}",
                url=tag_url, project_name=project_name,
                webhook_url=webhook_config["webhook_url"],
            )
            log.info("  Sent Google Chat notification")
    except Exception:
        log.exception("  Failed to send Google Chat notification")

    try:
        await db.save_event(
            event_type="release_notes",
            project_id=project_id,
            project_name=project_name,
            ref_id=tag,
            ref_url=tag_url,
            model=config.OLLAMA_MODEL,
            result_text=notes,
        )
    except Exception:
        log.exception("  Failed to save event to DB")

    log.info("========== RELEASE NOTES DONE in %.1fs ==========", time.monotonic() - t_start)


async def handle_release(payload: dict) -> None:
    action = payload.get("action")
    if action != "create":
        log.info("Release ignored: action=%s (only processing creates)", action)
        return

    project = payload.get("project") or {}
    project_id = project.get("id")
    project_name = project.get("path_with_namespace") or project.get("name") or "unknown"
    tag = payload.get("tag") or ""

    if not project_id or not tag:
        log.info("Release ignored: missing project_id or tag")
        return

    await _handle_release_for_tag(project_id, project_name, tag, project.get("web_url", ""))


async def handle_tag_push(payload: dict) -> None:
    project = payload.get("project") or {}
    project_id = project.get("id")
    project_name = project.get("path_with_namespace") or project.get("name") or "unknown"
    ref = payload.get("ref", "")
    tag = ref.replace("refs/tags/", "")

    checkout_sha = payload.get("checkout_sha") or payload.get("after", "")
    if not checkout_sha or checkout_sha == "0" * 40:
        log.info("Tag push ignored: tag '%s' was deleted", tag)
        return

    if not project_id or not tag:
        log.info("Tag push ignored: missing project_id or tag")
        return

    await _handle_release_for_tag(project_id, project_name, tag, project.get("web_url", ""))
